Alibaba-Nacos:
  - "/nacos/"
  - "/api/nacos/"
Alibaba-Druid:
  - "/druid/index.html"
泛微-协同办公OA:
  - "/wui/index.html"
vmware-SpringBoot-Framework:
  - "/error"
  - "/gateway/error/"
  - "/api/error/"
ThinkPHP:
  - "/?a=WKtwuea&c=2RVM&m=fv3C&s=ba5a"
帆软-FineReport:
  - "/WebReport/ReportServer"
  - "/ReportServer"
  - "/webroot/decision/login"
XXL-JOB:
  - "/xxl-job-admin/toLogin"
  - "/xxl-job/toLogin"
  - "/xxl/toLogin"
GeoServer:
  - "/geoserver/web/"
百度-UEditor:
  - "/ueditor/ueditor.all.js"
  - "/js/ueditor/ueditor.all.js"
易软天创-禅道系统:
  - "/zentao/"
phpMyAdmin:
  - "/phpmyadmin/"
  - "/pma/"
ArcGIS:
  - "/arcgis/"
SMARTBI:
  - "/smartbi/vision/index.jsp"
HARBOR:
  - "/harbor/"
MINIO-Browser:
  - "/minio/"
Tomcat-Login:
  - "/manager/html"
Jenkins:
  - "/jenkins/login"