id: idocview-cmd-rce

info:
  name: iDocView cmd.json RCE
  author: SleepingBag945
  severity: critical

http:
  - raw:
      - |
        GET /system/cmd.json HTTP/1.1
        Host: {{Hostname}}

    matchers-condition: and
    matchers:
      - type: status
        part: status_code
        status:
          - 200
      - type: word
        part: body
        words:
          - '"code":"1"'
        condition: and
